version: 2.1

jobs:
  compile-linux-community:
    docker:
      - image: arangodb/build-alpine-x86_64:gcc11.2-openssl1.1.1s
    resource_class: large
    environment:
      GIT_SSH_COMMAND: ssh -v
    steps:
      - run:
          name: Print environment
          command: bash -c "echo $(nproc)"
      - restore_cache:
          keys:
            - gitcache-v1
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - save_cache:
          when: always
          key: gitcache-v1
          paths:
            - .git
      - run:
          name: Print CCache Settings
          command: ccache -p
      - restore_cache:
          keys:
            - ccache-v1-docker-{{ .Branch }}-{{ .Revision }}
            - ccache-v1-docker-{{ .Branch }}-
            - ccache-v1-docker
      - run:
          name: Zero CCache Statistics
          command: ccache -z
      - run:
          name: Configure
          command: |
            # the -DUSE_LIBUNWIND=1 is a hack that I would like to avoid in the future
            cmake --preset community-developer -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DUSE_LIBUNWIND=1
      - run:
          name: Build
          command: |
            cmake --build --preset community-developer --parallel 6 --target arangodbtests
      - run:
          name: CCache Statistics
          command: ccache -s
      - store_artifacts:
          path: build/community-developer/bin/arango*
      - save_cache:
          when: always
          key: ccache-v1-docker-{{ .Branch }}-{{ .Revision }}
          paths:
            - /root/.cache/ccache
      - persist_to_workspace:
          root: .
          paths:
            - build/bin
            - scripts/
            - js/
            - etc/
            - tests/js
            - utils
            - UnitTests

  run-gtest-executable-linux:
    parameters:
      executable:
        type: string
    docker:
      - image: arangodb/build-alpine-x86_64:gcc11.2-openssl1.1.1s
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Enabled coredumps
          command: ulimit -c unlimited
      - run:
          name: Run GTest
          command: |
            << parameters.executable >> --gtest_output=xml
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
      - store_test_results:
          path: test_detail.xml

  testing-js-run-test-suite:
    parameters:
      suite:
        type: string
      bucketCount:
        type: integer
        default: 1
      bucketIndex:
        type: integer
        default: 0
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Enabled coredumps
          command: ulimit -c unlimited
      - run:
          name: Run << parameters.suite >> suite
          command: |
            scripts/unittest << parameters.suite >> --cluster true --cleanup false --writeXmlReport true --dumpAgencyOnError true --testBuckets << parameters.bucketCount >>/<< parameters.bucketIndex >>
      - store_artifacts:
          destination: << parameters.suite >>
          path: out/*
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
      - store_artifacts:
          destination: << parameters.suite >>
          path: /tmp/*


workflows:
  devel-pr:
    when:
      matches:
        pattern: /^(bug-fix|feature|chore)\/.*$/
        value: << pipeline.git.branch >>
    jobs:
      - compile-linux-community
      - run-gtest-executable-linux:
          name: arangodbtests linux
          executable: 'build/community-developer/bin/arangodbtests'
          requires:
            - compile-linux-community
