version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    steps:
      #- checkout # checkout code
      #- run: # run a command
      #    name: Generate config
      #    command: |
      #      ./generate-config > generated_config.yml
      - continuation/continue:
          configuration_path: base_config.yml # use newly generated config to continue

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - setup
