version: 2.1

jobs:
  compile-linux-community:
    parameters:
      preset:
        type: string
    docker:
      - image: arangodb/build-alpine-x86_64:gcc11.2-openssl1.1.1s
    resource_class: xlarge
    environment:
      GIT_SSH_COMMAND: ssh -v
    steps:
      - run: git clone --depth 1 https://github.com/arangodb/arangodb.git -b "$CIRCLE_BRANCH" --recurse-submodules --shallow-submodules -j 8 /root/project
      - run:
          name: Print CCache Settings
          command: ccache -p
      - restore_cache:
          keys:
            - ccache-v1-docker-{{ .Branch }}-{{ .Revision }}
            - ccache-v1-docker-{{ .Branch }}-
            - ccache-v1-docker
      - run:
          name: Zero CCache Statistics
          command: ccache -z
      - run:
          name: Configure
          command: |
            cmake --preset << parameters.preset >> -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld"
      - run:
          name: Build
          command: |
            cmake --build --preset << parameters.preset >> --parallel 8 --target arangodbtests --target arangod --target arangosh --target arango 
      - run:
          name: CCache Statistics
          command: ccache -s
      - store_artifacts:
          path: build/<< parameters.preset >>/bin/arango*
      - save_cache:
          when: always
          key: ccache-v1-docker-{{ .Branch }}-{{ .Revision }}
          paths:
            - /root/.cache/ccache
      - persist_to_workspace:
          root: .
          paths:
            - build/<< parameters.preset >>/bin
            - scripts/
            - js/
            - etc/
            - tests/js
            - utils
            - UnitTests
            - 3rdParty/iresearch/tests/resources

  run-gtest-executable-linux:
    parameters:
      executable:
        type: string
      filter:
        type: string
    docker:
      - image: arangodb/build-alpine-x86_64:gcc11.2-openssl1.1.1s
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Enabled coredumps
          command: ulimit -c unlimited
      - run:
          name: Run GTest
          command: |
            << parameters.executable >> --gtest_filter=<< parameters.filter >> --gtest_output=xml
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
      - store_test_results:
          path: test_detail.xml

  testing-js-run-test-suite:
    parameters:
      suite:
        type: string
      bucketCount:
        type: integer
        default: 1
      bucketIndex:
        type: integer
        default: 0
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Enabled coredumps
          command: ulimit -c unlimited
      - run:
          name: Run << parameters.suite >> suite
          command: |
            scripts/unittest << parameters.suite >> --cluster true --cleanup false --writeXmlReport true --dumpAgencyOnError true --testBuckets << parameters.bucketCount >>/<< parameters.bucketIndex >>
      - store_artifacts:
          destination: << parameters.suite >>
          path: out/*
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
      - store_artifacts:
          destination: << parameters.suite >>
          path: /tmp/*


workflows:
  devel-pr:
    when:
      matches:
        pattern: /^(bug-fix|feature|chore)\/.*$/
        value: << pipeline.git.branch >>
    jobs:
      - compile-linux-community:
          name: build-community-pr
          preset: community-pr
      - run-gtest-executable-linux:
          name: arangodbtests linux
          executable: 'build/community-pr/bin/arangodbtests'
          filter: '-*_LongRunning:-IResearch*:-*Replication2*' 
          requires:
            - build-community-pr
      - run-gtest-executable-linux:
          name: iresearch arangodbtests linux
          executable: 'build/community-pr/bin/arangodbtests'
          filter: 'IResearch*' 
          requires:
            - build-community-pr
       - run-gtest-executable-linux:
          name: iresearch arangodbtests linux
          executable: 'build/community-pr/bin/arangodbtests'
          filter: '*Replication2*' 
          requires:
            - build-community-pr
 
